import './globals.css'
import { Istok_Web } from 'next/font/google'
import Header from '@/components/header'

const istokWeb = Istok_Web({
  subsets: ['latin'], weight: ['400', '700'], style: ['normal']
})

export const metadata = {
  title: 'Apps',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={istokWeb.className}>
        <main>{children}</main>
      </body>
    </html>
  )
}
